// Side-effect Imports: each resource module registers itself into the shared
// `scheme` (object-meta.ts) at import time.
import "./agent.ts"
import "./azure-foundry-model.ts"
import "./mcp-stdio.ts"
import "./memory.ts"
import "./ollama-model.ts"
import "./openai-model.ts"
import "./posture.ts"
import "./preset.ts"
import "./skill.ts"

export type { AgentManifest, AgentSpec, AgentStatus } from "./agent.ts"
export type { AzureFoundryModelManifest, AzureFoundryModelSpec } from "./azure-foundry-model.ts"
export type { McpStdioManifest, McpStdioSpec, McpStdioStatus } from "./mcp-stdio.ts"
export type { MemoryManifest, MemorySpec } from "./memory.ts"
export type { OllamaModelManifest, OllamaModelSpec } from "./ollama-model.ts"
export type { OpenAIModelManifest, OpenAIModelSpec } from "./openai-model.ts"
export type { PostureManifest, PostureSpec, PostureStatus } from "./posture.ts"
export type { PresetManifest, PresetSpec } from "./preset.ts"
export type { SkillManifest, SkillSpec, SkillStatus } from "./skill.ts"

export { BaseModelObject, type ModelStatus } from "./model-base.ts"
export { AgentObject, AGENT_API_VERSION } from "./agent.ts"
export { AzureFoundryModelObject } from "./azure-foundry-model.ts"
export { McpStdioObject } from "./mcp-stdio.ts"
export { MemoryObject } from "./memory.ts"
export { OllamaModelObject } from "./ollama-model.ts"
export { OpenAIModelObject } from "./openai-model.ts"
export { PostureObject } from "./posture.ts"
export { PresetObject } from "./preset.ts"
export { SkillObject } from "./skill.ts"

export type { KnownManifest } from "./known.ts"
